#!/usr/bin/env bash
# Update nix flake inputs, then commit and push a unique
# chore/flake-update-<timestamp> branch.
#
# Deliberately does NOT:
#   - run `nix fmt` (it rewrites unrelated files with pre-existing drift)
#   - regenerate the vendored IFD-workaround files (pkgs/opencode/*.nix,
#     pkgs/claude-session/skill/SKILL.md) — those belong to the package
#     update scripts. If a nixpkgs bump invalidates one of them (e.g. the
#     pinned pnpm version moves and breaks opencode's pnpmDeps hash), CI
#     fails and the PR simply waits for a human. That's intentional.
#   - touch the virby input: it is pinned to a rev in its flake.nix URL,
#     so `nix flake update` correctly leaves it alone.
#
# Writes step outputs to $GITHUB_OUTPUT:
#   changed    "true"  if the branch was pushed (gate for the PR step)
#              "false" if nothing changed or DRY_RUN=true
#   title      Conventional-commit PR title
#   body_file  Path to a markdown file with the full PR body
#   branch     Name of the pushed branch
#
# Required env (auto-provided under Forgejo Actions):
#   GITHUB_OUTPUT      writable file for step output key=value pairs
#
# Optional env:
#   DRY_RUN  "true" → print what would change but skip commit/push

set -euo pipefail

DRY_RUN="${DRY_RUN:-false}"

# Print tool identities up front so env drift is visible in every CI log.
echo "==> Toolchain:"
echo "    $(nix --version) ($(command -v nix))"
echo "    $(git --version) ($(command -v git))"
echo "    CI=${CI:-<unset>}"

write_output() {
  if [ -n "${GITHUB_OUTPUT:-}" ]; then
    echo "$1" >> "$GITHUB_OUTPUT"
  fi
  echo "output: $1"
}

# ── 1. Update flake inputs ───────────────────────────────────────────────────

echo "==> Updating nix flake inputs..."
# nix flake update writes progress to stderr; capture both streams for the PR body.
nix_output=$(nix flake update 2>&1) || true
echo "$nix_output"

# ── 2. Detect changes ────────────────────────────────────────────────────────

if [ -z "$(git status --porcelain flake.lock)" ]; then
  echo "==> flake.lock unchanged. No PR needed."
  write_output "changed=false"
  exit 0
fi

title="chore(deps): update nix flake inputs"

# ── 3. Build PR body ─────────────────────────────────────────────────────────

body_file="/tmp/update-flake-body.md"
{
  echo "## Nix flake input updates"
  echo ""
  echo '```'
  echo "$nix_output" | grep -iE "updated input|•|→" || echo "$nix_output"
  echo '```'
  echo ""
  echo "Merge is gated on the full \`ci\` workflow: flake check, every"
  echo "package/devShell/home activation on all three platforms, and the"
  echo "ada/flamme/lux/roxy host closures."
  echo ""
  echo "---"
  echo "_Generated by \`update-flake\` workflow · $(date -u '+%Y-%m-%d')_"
} > "$body_file"

cat "$body_file"

# ── 4. Write outputs / commit / push ─────────────────────────────────────────

write_output "title=${title}"
write_output "body_file=${body_file}"

if [ "$DRY_RUN" = "true" ]; then
  echo "==> Dry run — skipping branch commit and push."
  write_output "changed=false"
  exit 0
fi

# Unique branch per run so a queued or in-flight PR is never clobbered.
# create-update-pr.sh closes any older open flake-update PRs afterwards.
stamp=$(date -u +%Y%m%d-%H%M%S)
branch="chore/flake-update-${stamp}"

echo "==> Committing to ${branch}..."
git switch -C "$branch"
git add flake.lock
git commit -m "$title"
git push origin "$branch"

echo "==> Branch pushed."
write_output "branch=${branch}"
write_output "changed=true"
